#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/housingms_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: myf020526@23
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: 8282